const FORCES = {
  pm: {
    name: 'Polícia Militar',
    tipoPermuta: 'PM',
    primary: '#1a365d',
    primaryDark: '#0f2027',
    primaryLight: '#2d4a6b',
    secondary: '#4a5568',
    background: '#f7fafc',
    headline: 'Encontre sua permuta na Polícia Militar de forma inteligente.',
    description: 'Conecte-se com colegas PM de todo o Brasil. Matches diretos, triangulares e por proximidade — com mapa nacional e motor inteligente.',
    metaDescription: 'Plataforma de permutas para Polícia Militar. Matches diretos, triangulares, mapa nacional e simulador de compatibilidade.',
    whyBenefit: 'A Polícia Militar opera em unidades espalhadas por todo o estado. O Permuta Policial conecta quem quer sair de uma OPM com quem quer entrar, incluindo permutas triangulares e ciclos maiores que viabilizam trocas impossíveis de encontrar sozinho.',
  },
  bm: {
    name: 'Bombeiros Militares',
    tipoPermuta: 'BM',
    primary: '#c53030',
    primaryDark: '#9b2c2c',
    primaryLight: '#e53e3e',
    secondary: '#d69e2e',
    background: '#fffaf0',
    headline: 'Encontre sua permuta nos Bombeiros Militares de forma inteligente.',
    description: 'Conecte-se com colegas bombeiros de todo o Brasil. Matches diretos, triangulares e por proximidade — com mapa nacional e motor inteligente.',
    metaDescription: 'Plataforma de permutas para Bombeiros Militares. Matches diretos, triangulares, mapa nacional e simulador de compatibilidade.',
    whyBenefit: 'Os Bombeiros Militares operam em unidades espalhadas por todo o estado. O Permuta Policial conecta quem quer sair de uma lotação com quem quer entrar, incluindo permutas triangulares e ciclos maiores que viabilizam trocas impossíveis de encontrar sozinho.',
  },
  pc: {
    name: 'Polícia Civil',
    tipoPermuta: 'PC',
    primary: '#1a202c',
    primaryDark: '#0d1117',
    primaryLight: '#2d3748',
    secondary: '#d4af37',
    background: '#fafafa',
    headline: 'Encontre sua permuta na Polícia Civil de forma inteligente.',
    description: 'Conecte-se com colegas da PC de todo o Brasil. Matches diretos, triangulares e por proximidade — com mapa nacional e motor inteligente.',
    metaDescription: 'Plataforma de permutas para Polícia Civil. Matches diretos, triangulares, mapa nacional e simulador de compatibilidade.',
    whyBenefit: 'A Polícia Civil opera em delegacias e regionais espalhadas por todo o estado. O Permuta Policial conecta quem quer sair de uma lotação com quem quer entrar, incluindo permutas triangulares e ciclos maiores que viabilizam trocas impossíveis de encontrar sozinho.',
  },
  prf: {
    name: 'Polícia Rodoviária Federal',
    tipoPermuta: 'PRF',
    primary: '#2c5282',
    primaryDark: '#1a365d',
    primaryLight: '#3182ce',
    secondary: '#d69e2e',
    background: '#ebf8ff',
    headline: 'Encontre sua permuta na PRF de forma inteligente.',
    description: 'Conecte-se com colegas da Polícia Rodoviária Federal em todo o Brasil. Matches diretos, triangulares e por proximidade — com mapa nacional e motor inteligente.',
    metaDescription: 'Plataforma de permutas para Polícia Rodoviária Federal. Matches diretos, triangulares, mapa nacional e simulador de compatibilidade.',
    whyBenefit: 'A PRF opera em bases e inspetorias espalhadas pelo país. O Permuta Policial conecta quem quer sair de uma lotação com quem quer entrar, incluindo permutas triangulares e ciclos maiores que viabilizam trocas impossíveis de encontrar sozinho.',
  },
  pf: {
    name: 'Polícia Federal',
    tipoPermuta: 'PF',
    primary: '#744210',
    primaryDark: '#5a2d0c',
    primaryLight: '#975a16',
    secondary: '#d4af37',
    background: '#fffaf0',
    headline: 'Encontre sua permuta na Polícia Federal de forma inteligente.',
    description: 'Conecte-se com colegas da PF em todo o Brasil. Matches diretos, triangulares e por proximidade — com mapa nacional e motor inteligente.',
    metaDescription: 'Plataforma de permutas para Polícia Federal. Matches diretos, triangulares, mapa nacional e simulador de compatibilidade.',
    whyBenefit: 'A Polícia Federal opera em unidades espalhadas por todo o país. O Permuta Policial conecta quem quer sair de uma lotação com quem quer entrar, incluindo permutas triangulares e ciclos maiores que viabilizam trocas impossíveis de encontrar sozinho.',
  },
  gm: {
    name: 'Guarda Municipal',
    tipoPermuta: 'GM',
    primary: '#1a365d',
    primaryDark: '#0f2027',
    primaryLight: '#2d4a6b',
    secondary: '#a0aec0',
    background: '#f7fafc',
    headline: 'Encontre sua permuta na Guarda Municipal de forma inteligente.',
    description: 'Conecte-se com colegas guardas de todo o Brasil. Matches diretos, triangulares e por proximidade — com mapa nacional e motor inteligente.',
    metaDescription: 'Plataforma de permutas para Guarda Municipal. Matches diretos, triangulares, mapa nacional e simulador de compatibilidade.',
    whyBenefit: 'A Guarda Municipal opera em unidades espalhadas pelos municípios. O Permuta Policial conecta quem quer sair de uma lotação com quem quer entrar, incluindo permutas triangulares e ciclos maiores que viabilizam trocas impossíveis de encontrar sozinho.',
  },
  pp: {
    name: 'Polícia Penal',
    tipoPermuta: 'PP',
    primary: '#44337a',
    primaryDark: '#322659',
    primaryLight: '#5a4a91',
    secondary: '#9f7aea',
    background: '#faf5ff',
    headline: 'Encontre sua permuta na Polícia Penal de forma inteligente.',
    description: 'Conecte-se com colegas da Polícia Penal de todo o Brasil. Matches diretos, triangulares e por proximidade — com mapa nacional e motor inteligente.',
    metaDescription: 'Plataforma de permutas para Polícia Penal. Matches diretos, triangulares, mapa nacional e simulador de compatibilidade.',
    whyBenefit: 'A Polícia Penal opera em unidades prisionais espalhadas por todo o estado. O Permuta Policial conecta quem quer sair de uma unidade com quem quer entrar, incluindo permutas triangulares e ciclos maiores que viabilizam trocas impossíveis de encontrar sozinho.',
  },
};

module.exports = { FORCES };
