# app.yaml - Configuração para LiteSpeed Node.js
runtime: nodejs
env: standard
instance_class: F1

# Versão do Node.js
runtime_config:
  nodejs_version: 19

# Variáveis de ambiente
env_variables:
  NODE_ENV: 'production'
  PORT: '3000'

# Configurações de rede
network:
  forwarded_ports:
    - 3000

# Health check
health_check:
  path: '/api'
  initial_delay_sec: 30
  check_interval_sec: 10